### ISSUE TITLE
[Bug] searchQuotes Number Offset when Page > 1

### ISSUE THREAD

**Issue by ForgedGrentleman** [AnonymousHacker1279/TitanBot#1]
goshdarnit i love to complain
Numbers when $sq @(user) (page) is sometimes offset from the actual quote number
I fix (win)

**Comment by AnonymousHacker1279** [comment]
I believe this is just a bug when gathering the quote numbers, meaning it shouldn't be related to the actual quote content. Meaning, shifting the `authorQuoteIndex` array to the left by 1 should fix it. For example:

```
embed.description += data[authorQuoteIndex[iteration] - 1]["content"] + " **Quote #" + str(
									authorQuoteIndex[iteration]) + "**\n"
```
becomes
```
embed.description += data[authorQuoteIndex[iteration] - 1]["content"] + " **Quote #" + str(
									authorQuoteIndex[iteration] - 1) + "**\n"
```

The particular area you need to be in is [here](https://github.com/AnonymousHacker1279/TitanBot/blob/71b3ba196b5041f645200f338991376d453108f8/Framework/CommandGroups/Quotes.py#L249). 

I would have fixed this simple issue myself by now, but I haven't had much free time.
